---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
   - name: verify apache
     uri:
       url: http://localhost
       status_code: 200